@echo off
setlocal
REM Example: run paper trading on the last signals CSV generated by scan_once
set INPUT_CSV=%1
set OUT_PDF=%2
if "%INPUT_CSV%"=="" (
  echo Usage: paper_trade.bat ^<signals.csv^> ^<out.pdf^>
  exit /b 1
)
if "%OUT_PDF%"=="" (
  set OUT_PDF=reports\performance_report.pdf
)
python -m src.cli.paper_trade %INPUT_CSV% %OUT_PDF%
endlocal
